In [ ]:
import numpy as np

array_1 = np.array([6, 10, 11, 1])

array_2 = np.array([4, 9, 16, 4])

print("Sum - ", array_1 + array_2)

print("Sub - ", array_1 - array_2)

print("Div - ", array_1 / array_2)

print("Mul - ", array_1 * array_2)

print("Squre - ", array_1**2)

print("sqrt - ", np.sqrt(array_2))

print("Sum Inbuild - ", np.sum(array_1))

print("Avg Inbuild - ", np.mean(array_1))

print("Max element - ", np.max(array_1))

print("Min elemenyt - ", np.min(array_1))

print("Index - ", array_1[2])

Sum -  [10 19 27  5]
Sub -  [ 2  1 -5 -3]
Div -  [1.5        1.11111111 0.6875     0.25      ]
Mul -  [ 24  90 176   4]
Squre -  [ 36 100 121   1]
sqrt -  [2. 3. 4. 2.]
Sum Inbuild -  28
Avg Inbuild -  7.0
Max element -  11
Min elemenyt -  1
Index -  11


2D

In [3]:
import numpy as np

array_2d = np.array([[1,2,3], [4,5,6]])

print(array_2d)
print(type(array_2d))
print("Shape - ", array_2d.shape)
print("Size - ", array_2d.size)
print("Dimension - ", array_2d.ndim)
print("Data Type - ", array_2d.dtype)
print("Index - ", array_2d[1, 1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Shape -  (2, 3)
Size -  6
Dimension -  2
Data Type -  int64
Index -  5


3D

In [2]:
import numpy as np

array_3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [5,9,3]]])

print(array_3d)
print(type(array_3d))
print("Shape - ",array_3d.shape)
print("Size - ", array_3d.size)
print(array_3d.ndim)
print(array_3d.dtype)
print("Index - ", array_3d[1, 0, 2])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 9 3]]]
<class 'numpy.ndarray'>
Shape -  (2, 2, 3)
Size -  12
3
int64
Index -  9


ARRAY INITIALIZE

In [4]:
import numpy as np

print(np.zeros(5))

print(np.zeros((2, 3), dtype=int))

print(np.full((3, 4), 7))

print(np.empty((2, 3)))

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
[[0. 0. 0.]
 [0. 0. 0.]]


BOOLEAN INDEXING

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

condition = arr > 25

print(condition)

[False False  True  True  True]


In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result_arr = arr[condition]

print(result_arr)

[30 40 50]


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[arr>25])

result = arr[(arr>25) & (arr<50)]

print(result)

[30 40 50]
[30 40]


EXERSICE

In [8]:
import numpy as np

arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
print(arr_2d.shape)

print("Sum 10 - ", arr_2d + 10)
print("Div 2 - ", arr_2d / 2)
print("Squre - ", arr_2d ** 2)

(4, 5)
Sum 10 -  [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Div 2 -  [[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]]
Squre -  [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print("Even numbers - ", arr[arr%2 == 0])

arr_2 = np.array([10, 20, 30, 40, 50])


print("Mean - ", arr_2[arr_2 > np.mean(arr_2)])

Even numbers -  [ 2  4  6  8 10 12 14 16 18 20]
Mean -  [40 50]
